baseURL = "https://freediveca.com/"
languageCode = "en-us"
title = "Freedive California"
theme = "minimal"
googleAnalytics = ""
publishDir = "docs"
canonifyURLs = true
    
[markup.goldmark.renderer]
  unsafe = true

[params]
    author = "CJ Jessett"
    description = "Freediving & Spearfishing Education, Training, and Guiding"
    githubUsername = "#"
    accent = "none"
    showBorder = true
    backgroundColor = "white"
    font = "Sourcecode Pro" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/calendar/"
    name = "Calendar"
    weight = 4

[[menu.main]]
    url = "/courses/"
    name = "Courses"
    weight = 3
    
[[menu.main]]
    url = "/conditions/"
    name = "Ocean Conditions"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@freedivaca.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://facebook.com/freedive.california/"
    name = "facebook"
    weight = 2

[[menu.icon]]
    url = "https://instagram.com/freedive.california/"
    name = "instagram"
    weight = 3
